name: PlayerManager
version: 1.0.2
main: ru.stepanyaa.playerManager.PlayerManager
license: MIT 
api-version: 1.16
commands:
 playermanager:
  description: A powerful and intuitive Minecraft plugin for efficient player management.
  usage: /<command> <gui | reload | reset | ban | kick | warn | mute | unban | teleport | inventory> [player]
  aliases: [pm]
permissions:
 playermanager.admin:
  description: Grants full access to all PlayerManager commands and update notifications
  default: op
  children:
   playermanager.gui: true
   playermanager.reload: true
   playermanager.ban: true
   playermanager.kick: true
   playermanager.warn: true
   playermanager.mute: true
   playermanager.unban: true
   playermanager.teleport: true
   playermanager.inventory: true
   playermanager.updates: true
 playermanager.gui:
  description: Allows access to the PlayerManager GUI
  default: op
  children:
   playermanager.reset: true
 playermanager.reload:
  description: Allows reloading the PlayerManager configuration
  default: op
 playermanager.reset:
  description: Allows resetting the PlayerManager search
  default: op
 playermanager.ban:
  description: Allows banning players using PlayerManager
  default: op
 playermanager.kick:
  description: Allows kicking players using PlayerManager
  default: op
 playermanager.warn:
  description: Allows warning players using PlayerManager
  default: op
 playermanager.mute:
  description: Allows muting players using PlayerManager
  default: op
 playermanager.unban:
  description: Allows unbanning players using PlayerManager
  default: op
 playermanager.teleport:
  description: Allows teleporting to players using PlayerManager
  default: op
 playermanager.inventory:
  description: Allows inspecting player inventories using PlayerManager
  default: op
 playermanager.updates:
  description: Allows receiving update notifications for PlayerManager
  default: op